production:
  solr:
    hostname: localhost
    port: 8983
    log_level: OFF
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5
    memory: 16M

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: OFF
    path: /solr/development
    memory: 32M

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: OFF
    path: /solr/test
    memory: 16M
    